{% set name = "cashews" %}
{% set version = "7.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cashews-{{ version }}.tar.gz
  sha256: dca761c60192bfe354abd6e9eb98d6f62c817e675df3fbe7d1bdfaa4303d1320

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cashews
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Krukov/cashews/
  summary: cache tools with async power
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
