{% set name = "cashews" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cashews-{{ version }}.tar.gz
  sha256: 3f88b8c5ced0ea4826915a1ff67055b647252dd65ef25f4813316a6341f00b37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cashews
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Krukov/cashews/
  summary: cache tools with async power
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
