{% set name = "cashews" %}
{% set version = "7.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/cashews-{{ version }}.tar.gz
  sha256: fc2456d9153ca424f26b040ef053d000f9092c65b1ad6e6330f66fea95d503f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cashews
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Krukov/cashews/
  summary: cache tools with async power
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
